/*
 * File: app/view/CascadingSelect.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CascadingSelect.view.CascadingSelect', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.cascadingselect',

    requires: [
        'CascadingSelect.view.CascadingSelectViewModel',
        'CascadingSelect.view.CascadingSelectViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.Label'
    ],

    controller: 'cascadingselect',
    viewModel: {
        type: 'cascadingselect'
    },
    scrollable: 'vertical',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'form',
            width: 500,
            bodyPadding: 10,
            title: 'Select Car',
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'makerField',
                    fieldLabel: 'Make',
                    labelAlign: 'right',
                    labelWidth: 70,
                    editable: false,
                    displayField: 'value',
                    valueField: 'id',
                    listeners: {
                        change: 'onMakerFieldChange'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'seriesField',
                    fieldLabel: 'Series',
                    labelAlign: 'right',
                    labelWidth: 70,
                    editable: false,
                    displayField: 'value',
                    valueField: 'id',
                    listeners: {
                        change: 'onSeriesFieldChange'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'modelField',
                    fieldLabel: 'Model',
                    labelAlign: 'right',
                    labelWidth: 70,
                    editable: false,
                    displayField: 'value',
                    valueField: 'id',
                    listeners: {
                        change: 'onModelFieldChange'
                    }
                },
                {
                    xtype: 'container',
                    margin: '10 0 10 0',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            reference: 'doneButton',
                            text: 'Choose Car',
                            listeners: {
                                click: 'onDoneButtonClick'
                            }
                        }
                    ]
                }
            ],
            listeners: {
                render: 'onFormRender'
            }
        },
        {
            xtype: 'panel',
            height: 800,
            padding: 10,
            width: 910,
            layout: 'fit',
            bodyPadding: 10,
            title: 'https://richtexteditor.com',
            items: [
                {
                    xtype: 'label',
                    html: '<div id="div_editor_boos"  style="min-height:300px;max-height:600px">        <p>Initial Document Ejemplo para BOOS SAS</p>      </div> '
                }
            ],
            listeners: {
                afterrender: 'onPanelWYSYAfterRender'
            }
        }
    ]

});